<?php
/**
 * Themeasy Assets Loader
 *
 * Centralized asset registration/enqueue:
 * - The design token defaults (tokens)
 * - Core CSS layers (core / components / effects / accessibility)
 * - Vendor libraries (Bootstrap, GLightbox)
 * - Optional modules (the lightbox module)
 * - Auto-registered widget assets (assets/widgets/**)
 *
 * @package Themeasy\Core
 * @since 1.0.0
 */

defined( 'ABSPATH' ) || exit;

/**
 * Cache-busting version for a first-party asset.
 *
 * Returns the file's modification time when readable — so edits to the in-place
 * .min source files bust browser/CDN caches between releases (the project's
 * documented convention) — and falls back to the plugin version otherwise.
 * Vendor libraries keep their own upstream version string.
 *
 * @param string $relative Asset path relative to the plugin root (e.g. 'assets/css/core.min.css').
 * @return string|int Version string or file mtime.
 */
function themeasy_asset_ver( string $relative ) {
  $path = THEMEASY_PATH . ltrim( $relative, '/' );

  return is_readable( $path ) ? filemtime( $path ) : themeasy_get_asset_version();
}

/**
 * Register vendor assets (JS/CSS).
 *
 * @return void
 */
function themeasy_register_vendor_assets() {
  // ------------------------------------------------------------------------
  // Vendor CSS: Bootstrap
  //
  // A Themeasy theme is built on Bootstrap's reboot: its style.css loads after
  // it and overrides it. On any other theme the reboot's element rules (body,
  // headings, links, lists) would restyle the host page, so it gets the same
  // release with those rules scoped to the Themeasy widgets, generated by the
  // repository's bootstrap-scoped.mjs script (backlog #265).
  // ------------------------------------------------------------------------
  if ( current_theme_supports( 'themeasy-compatible' ) ) {
    wp_register_style(
      'themeasy-bootstrap',
      THEMEASY_URL . 'assets/css/vendor/bootstrap.min.css',
      [],
      '5.3.8'
    );
  } else {
    wp_register_style(
      'themeasy-bootstrap',
      THEMEASY_URL . 'assets/css/vendor/bootstrap-scoped.min.css',
      [],
      themeasy_asset_ver( 'assets/css/vendor/bootstrap-scoped.min.css' )
    );
  }

  // ------------------------------------------------------------------------
  // Vendor JS: Bootstrap
  // ------------------------------------------------------------------------
  wp_register_script(
    'themeasy-bootstrap',
    THEMEASY_URL . 'assets/js/vendor/bootstrap.bundle.min.js',
    [],
    '5.3.8',
    true
  );

  // ------------------------------------------------------------------------
  // Vendor CSS: GLightbox
  // ------------------------------------------------------------------------
  wp_register_style(
    'themeasy-glightbox',
    THEMEASY_URL . 'assets/css/vendor/glightbox.min.css',
    [],
    '3.3.1'
  );

  // ------------------------------------------------------------------------
  // Vendor JS: GLightbox
  // ------------------------------------------------------------------------
  wp_register_script(
    'themeasy-glightbox',
    THEMEASY_URL . 'assets/js/vendor/glightbox.min.js',
    [],
    '3.3.1',
    true
  );
}
add_action( 'wp_enqueue_scripts', 'themeasy_register_vendor_assets', 5 );

/**
 * Register Themeasy modules (optional feature files).
 *
 * Modules are loaded on-demand by widgets via get_style_depends() /
 * get_script_depends() or a manual enqueue.
 *
 * @return void
 */
function themeasy_register_modules_assets() {
  // ------------------------------------------------------------------------
  // Module CSS: Lightbox
  // ------------------------------------------------------------------------
  wp_register_style(
    'themeasy-lightbox-module',
    THEMEASY_URL . 'assets/css/modules/lightbox.min.css',
    ['themeasy-glightbox'],
    themeasy_asset_ver( 'assets/css/modules/lightbox.min.css' )
  );

  // ------------------------------------------------------------------------
  // Module JS: Lightbox
  // ------------------------------------------------------------------------
  wp_register_script(
    'themeasy-lightbox-module',
    THEMEASY_URL . 'assets/js/modules/lightbox.min.js',
    ['themeasy-glightbox'],
    themeasy_asset_ver( 'assets/js/modules/lightbox.min.js' ),
    true
  );

  // Plyr, GLightbox's video player, served from the plugin. GLightbox injects
  // it lazily when a video slide opens, from cdn.plyr.io by default, and Plyr
  // pulls its icon sprite from there too (backlog #257). The version in the
  // URLs is the one of the files in assets/*/vendor/: bump the two together.
  wp_localize_script(
    'themeasy-lightbox-module',
    'themeasyLightbox',
    [
      'plyr' => [
        'css' => THEMEASY_URL . 'assets/css/vendor/plyr.min.css?ver=3.8.5',
        'js' => THEMEASY_URL . 'assets/js/vendor/plyr.min.js?ver=3.8.5',
        'iconUrl' => THEMEASY_URL . 'assets/js/vendor/plyr.svg?ver=3.8.5',
      ],
    ]
  );
}
add_action( 'wp_enqueue_scripts', 'themeasy_register_modules_assets', 6 );

/**
 * Enqueue core Themeasy assets.
 *
 * Loads the CSS layers in cascade order (core → components → effects →
 * accessibility), after the design token defaults they all consume. All of
 * them load globally for now. No core JS loads here: the widgets need none,
 * and the one that needs Bootstrap JS (the Accordion) declares it itself.
 *
 * @return void
 */
function themeasy_enqueue_core_assets() {
  // ------------------------------------------------------------------------
  // Design tokens: the --tms-* defaults at zero specificity, so the widgets
  // render on any theme. On a Themeasy theme, its style.css and the generated
  // settings.css outrank them (backlog #256).
  // ------------------------------------------------------------------------
  wp_enqueue_style(
    'themeasy-tokens',
    THEMEASY_URL . 'assets/css/tokens.min.css',
    [],
    themeasy_asset_ver( 'assets/css/tokens.min.css' )
  );

  // ------------------------------------------------------------------------
  // Core CSS
  // ------------------------------------------------------------------------
  wp_enqueue_style(
    'themeasy-core',
    THEMEASY_URL . 'assets/css/core.min.css',
    ['themeasy-bootstrap'],
    themeasy_asset_ver( 'assets/css/core.min.css' )
  );

  // ------------------------------------------------------------------------
  // Components CSS
  // ------------------------------------------------------------------------
  wp_enqueue_style(
    'themeasy-components',
    THEMEASY_URL . 'assets/css/components.min.css',
    ['themeasy-core'],
    themeasy_asset_ver( 'assets/css/components.min.css' )
  );

  // ------------------------------------------------------------------------
  // Effects CSS
  // ------------------------------------------------------------------------
  wp_enqueue_style(
    'themeasy-effects',
    THEMEASY_URL . 'assets/css/effects.min.css',
    ['themeasy-core'],
    themeasy_asset_ver( 'assets/css/effects.min.css' )
  );

  // ------------------------------------------------------------------------
  // Accessibility CSS
  // ------------------------------------------------------------------------
  wp_enqueue_style(
    'themeasy-accessibility',
    THEMEASY_URL . 'assets/css/accessibility.min.css',
    ['themeasy-effects'],
    themeasy_asset_ver( 'assets/css/accessibility.min.css' )
  );
}
add_action( 'wp_enqueue_scripts', 'themeasy_enqueue_core_assets', 10 );

/**
 * Register the widgets' CSS and JS files.
 *
 * @return void
 */
function themeasy_auto_register_widget_assets() {
  themeasy_register_widget_assets_in( 'assets/widgets/' );
}
add_action( 'wp_enqueue_scripts', 'themeasy_auto_register_widget_assets', 7 );

/**
 * Register every widget CSS and JS file under one asset root.
 *
 * A file placed directly in the root (e.g. bundle.min.css) registers as
 * themeasy-{basename}; a file inside a subdirectory registers as
 * themeasy-{folder}, so the handle follows the widget slug.
 *
 * @param string $relative Asset root relative to the plugin root (e.g. 'assets/widgets/').
 * @return void
 */
function themeasy_register_widget_assets_in( string $relative ): void {
  $base_path = trailingslashit( THEMEASY_PATH . ltrim( $relative, '/' ) );
  $base_url = trailingslashit( THEMEASY_URL . ltrim( $relative, '/' ) );
  $version = themeasy_get_asset_version();

  if ( !is_dir( $base_path ) ) {
    return;
  }

  $items = scandir( $base_path );

  foreach ( $items as $item ) {
    if ( in_array( $item, ['.', '..'], true ) ) {
      continue;
    }

    $item_path = $base_path . $item;
    $item_url = $base_url . $item;

    // Direct files in /widgets/ (e.g. bundle.min.css).
    if ( is_file( $item_path ) ) {
      themeasy_register_asset_from_file( $item, $base_path, $base_url, $version );
      continue;
    }

    // Subdirectories like /slider/, /image-distortion/, etc.
    if ( is_dir( $item_path ) ) {
      $widget_files = glob( trailingslashit( $item_path ) . '*.{css,js}', GLOB_BRACE );

      if ( empty( $widget_files ) ) {
        continue;
      }

      foreach ( $widget_files as $file_path ) {
        $file_name = basename( $file_path );
        themeasy_register_asset_from_file( $file_name, trailingslashit( $item_path ), trailingslashit( $item_url ), $version, $item );
      }
    }
  }
}

/**
 * Register a single CSS or JS file as a WordPress asset.
 *
 * @param string      $filename File name (e.g. slider.min.css).
 * @param string      $path     Full absolute path to the file directory (used for filemtime cache busting).
 * @param string      $url      Public URL to the file directory.
 * @param string      $version  Version string for cache busting.
 * @param string|null $prefix   Optional prefix used as the handle base (usually subfolder name).
 * @return void
 */
function themeasy_register_asset_from_file( string $filename, string $path, string $url, string $version, ?string $prefix = null ): void {
  // ------------------------------------------------------------------------
  // Handle and URL generation.
  // ------------------------------------------------------------------------
  $ext = pathinfo( $filename, PATHINFO_EXTENSION );

  // Remove ".min" from basename if present.
  $basename = preg_replace( '/\.min$/', '', pathinfo( $filename, PATHINFO_FILENAME ) );
  $basename = sanitize_key( $basename );

  // Final handle.
  $handle = $prefix ? "themeasy-{$prefix}" : "themeasy-{$basename}";
  $file_url = $url . $filename;

  // ------------------------------------------------------------------------
  // Dependencies (registration-time load order; see themeasy_get_widget_asset_deps()).
  // ------------------------------------------------------------------------
  $deps = themeasy_get_widget_asset_deps();
  $style_deps = array_values( array_filter( (array) ( $deps['style'][$handle] ?? [] ) ) );
  $script_deps = array_values( array_filter( (array) ( $deps['script'][$handle] ?? [] ) ) );

  // ------------------------------------------------------------------------
  // Register the asset based on its type. Use the file mtime for cache busting
  // when readable, so in-place edits to the .min sources invalidate caches.
  // ------------------------------------------------------------------------
  $file_path = $path . $filename;
  $asset_ver = is_readable( $file_path ) ? filemtime( $file_path ) : $version;

  if ( 'css' === $ext ) {
    wp_register_style( $handle, $file_url, $style_deps, $asset_ver );
    return;
  }

  if ( 'js' === $ext ) {
    wp_register_script( $handle, $file_url, $script_deps, $asset_ver, true );
    return;
  }
}

/**
 * Registration-time dependency maps for auto-registered widget assets.
 *
 * Some widgets have implicit dependencies on vendor libraries or modules. They
 * only define dependency order at registration time: WordPress uses them to
 * guarantee the load order even when only the widget handle itself is enqueued
 * later (e.g. GLightbox loading after the video widget).
 *
 * An entry applies only to a handle that really registers the matching file
 * type. The map is filterable.
 *
 * @return array{script: array<string, string[]>, style: array<string, string[]>}
 */
function themeasy_get_widget_asset_deps(): array {
  static $deps = null;

  if ( null !== $deps ) {
    return $deps;
  }

  $script_deps_map = [
    'themeasy-image' => ['themeasy-lightbox-module'],
    // Video only needs GLightbox for its Lightbox play mode; the map keeps the load order safe for it.
    'themeasy-video' => ['themeasy-lightbox-module'],
  ];

  $style_deps_map = [
    'themeasy-image' => ['themeasy-lightbox-module'],
    'themeasy-video' => ['themeasy-lightbox-module'],
  ];

  /**
   * Filters the widget asset dependency maps.
   *
   * @param array $deps { script: handle => deps[], style: handle => deps[] }
   */
  $deps = (array) apply_filters(
    'themeasy/widget_asset_deps',
    [
      'script' => $script_deps_map,
      'style' => $style_deps_map,
    ]
  );

  return $deps;
}
